export const REVIEWS = [
  {
    id: 'ahmed-jeffrey',
    reviewer: 'Ahmed Jeffrey',
    headline: 'Flawless services',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'June 15, 2026',
    body: ['Flawless services! Definitely recommended.'],
  },
  {
    id: 'guita-kurd',
    reviewer: 'Guita Kurd',
    headline: 'Unprofessional experience',
    rating: 1,
    country: 'US',
    reviewCount: 1,
    date: 'July 28, 2025',
    body: [
      'I had a deeply disappointing experience with Crystal Web Solution. From the start, communication was inconsistent and concerning. Despite being the primary client, my emails were often ignored by a representative named Ethan—yet he responded promptly to my husband. This raised serious concerns about professionalism and respect.',
      'I paid for a website design service, which was delayed repeatedly. After weeks of little progress, I suddenly received five emails in one day demanding an additional $700 for hosting. Trusting the process, I paid the amount—only to face further delays and excuses. My emails were mysteriously “not received,” and I was left in the dark.',
      'We finally decided to terminate the contract on May 7, 2025, but even then, Ethan demanded more money from my husband just to release the WordPress files and other essential information for migration. This felt like a hostage situation for our own content.',
      'As of July 28, we’ve finally migrated to a new provider—after months of stress, lost time, and no refund for the $700 hosting fee I paid for my own site (separate from my husband’s).',
      'I’ve never encountered such unprofessional behavior in my career. I do not recommend Crystal Web Solution to anyone. If you’ve already paid them, consider cutting your losses and moving on.',
    ],
  },
  {
    id: 'ma-p',
    reviewer: 'MA P',
    headline: 'they are scammers and they claim thet…',
    rating: 1,
    country: 'PK',
    reviewCount: 1,
    date: 'February 21, 2024',
    body: ['they are scammers and they claim thet are in usa but they all are asian. they have scammed me around 3000 usa dollars. dont acheive their service ,scammers'],
  },
  {
    id: 'porsha-patterson',
    reviewer: 'Porsha Patterson',
    company: 'Zues Towing',
    headline: 'I was completely impressed with their…',
    rating: 5,
    country: 'US',
    reviewCount: 2,
    date: 'December 31, 2023',
    body: ['I was completely impressed with their professionalism and customer service. I will definitely be contacting them for future work.'],
  },
  {
    id: 'sneha-yendluri',
    reviewer: 'Sneha Yendluri',
    headline: 'The company was able to cater to the…',
    rating: 4,
    country: 'US',
    reviewCount: 1,
    date: 'April 27, 2023',
    body: ['The company was able to cater to the customer requirements. They were also really respectful on meeting the agenda on time. We had a lot of meetings going over different changes and Sheldon helped a lot.'],
  },
  {
    id: 'vaughn-hebron',
    reviewer: 'Vaughn Hebron',
    headline: 'For me the customer service was…',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'April 24, 2023',
    body: ['For me the customer service was everything! How do they treat you when the website has been built & they have been paid. Do they still answer your questions & provide service? And the answer was YES YES YES…'],
  },
  {
    id: 'ruben-coto',
    reviewer: 'Ruben Coto',
    headline: 'Ethan and his team were awesome and …',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'April 18, 2023',
    body: ['Ethan and his team were awesome and 100% on point. I appreciate all of their help and expertise.'],
  },
  {
    id: 'interconnect-business-network',
    reviewer: 'Interconnect Business Network',
    headline: 'Great customer service',
    rating: 5,
    country: 'US',
    reviewCount: 3,
    date: 'April 17, 2023',
    body: ['They always available to resolve customers inquiries'],
    reply: {
      date: 'April 17, 2023',
      body: 'Thankyou so much for the kind words Derrick. We hope Interconnect Business Network becomes a worldwide success.',
    },
  },
  {
    id: 'sweep-dreams-cleaning-service',
    reviewer: 'Sweep Dreams Cleaning Service',
    headline: 'Incredible Experience, these guys are the REAL DEAL!!',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'April 7, 2023',
    body: ['Wow. What can I say. My experience with Alex and the rest of the crew at Crystal Web Solution has been nothing short of amazing. These guys are the real deal. Not only did they create a completely custom WordPress website that included vector animations, third-party, CRM software integration, as well as customer outreach capabilities, they tailored a blog to my specific industry and helped my SEO incredibly in the beginning stages of my business. Alex and Sheldon were patient kind and understanding on the phone even when my original host crashed, and it took them hours of troubleshooting over the phone. I would recommend this company highly to anyone looking to design a website. My business has already profited from their expertise and yours will, too, if you give them an opportunity!! I’m looking to continue working with them in future. Thanks again Alex and Sheldon for running such a committed operation.'],
    reply: {
      date: 'April 17, 2023',
      body: 'Thanks Ryan for this amazing feedback. We loved working with you to bring Sweep Dreams Cleaning to inception.',
    },
  },
  {
    id: 'prestige',
    reviewer: 'Prestige',
    headline: 'I had an educational website made by…',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'February 23, 2023',
    body: ['I had an educational website made by Ethan and her team. I explained everything I needed done and gave her a deadline. Her team was able to have my website up and running within two weeks. I would definitely use them again.'],
  },
  {
    id: 'marta',
    reviewer: 'Marta',
    headline: 'Very flexible and great in theirs field but gaps in communication along the way',
    rating: 4,
    country: 'US',
    reviewCount: 1,
    date: 'February 20, 2023',
    body: ['The team was very flexible with any changes I wanted to get done and really created my vision to life. Everything was great other than a little bit of a communication barrier that I felt was happening during the process.'],
  },
  {
    id: 'buzimba',
    reviewer: 'Buzimba',
    headline: 'I am so glad to work with this web…',
    rating: 5,
    country: 'US',
    reviewCount: 5,
    date: 'February 20, 2023',
    body: [
      'I am so glad to work with this web designer company because this people are very helpful and they have a lot experience in what they do.',
      'Ethan,is the person who I talked to her and she did all her best to assist me and she really helped me beyond my expectations. Thank you Ethan for your help and God bless you.',
    ],
  },
  {
    id: 'tikishia-jenkins',
    reviewer: 'Tikishia Jenkins',
    headline: 'Very trustworthy',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'January 20, 2023',
    body: ["Very trustworthy, the GNZ Solutions team really help my business understand what's best and the correct packages to choose to get the best solutiom so that our website can be a success. Alex really breaks down for me what is beneficial and easy for me to share good information to my team. If you select this business you are making a great decision."],
  },
  {
    id: 'china-davis',
    reviewer: 'China Davis',
    headline: 'This is a scam agency',
    rating: 1,
    country: 'US',
    reviewCount: 1,
    date: 'January 19, 2023',
    body: ['This is a scam agency. Do not trust them with your money or anything. You are on your own'],
    reply: {
      date: 'January 19, 2023',
      body: 'We do not have a client with your name in our database. If you can please tell us your correct name, we will definitely look into what went wrong.',
    },
  },
  {
    id: 'rose-filicetti',
    reviewer: 'Rose Filicetti',
    headline: 'Quick Response',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'November 23, 2022',
    body: ['I needed someone who could work with me quickly in order to make an extremely close deadline. Ethan of Crystal Web Solution was and is the person I needed. Not only does he have excellent knowledge of web design, he also has a great ability to converse in a non-technical manner. I am looking forward to a continued relationship with Crystal Web Solution and especially Ethan.'],
  },
  {
    id: 'marcus',
    reviewer: 'Marcus',
    headline: 'I worked directly with Ethan',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'November 21, 2022',
    body: ['I worked directly with Ethan, who managed the project from start to finish and is very professional. The time frame they gave me to complete the project was accurate, and I am very thankful that he resolved the minor issues quickly. I would work with this company again, especially with Ethan.', 'Best,', 'Marcus'],
  },
  {
    id: 'orion',
    reviewer: 'Orion',
    headline: 'Great Customer Serive',
    rating: 5,
    country: 'US',
    reviewCount: 3,
    date: 'November 18, 2022',
    body: ['Ethan provided high quality and prompt customer service and made all requested modifications in route to delivering the website that I wanted.'],
  },
  {
    id: 'john-duncan',
    reviewer: 'John Duncan',
    headline: 'Ethan Ray was very professional',
    rating: 5,
    country: 'US',
    reviewCount: 3,
    date: 'August 16, 2022',
    body: ["Ethan Ray was very helpful, patient, and courteous. I am presently still working with him and I'm confident he'll continue his professional service.", "I'll gladly recommend him to anyone."],
  },
  {
    id: 'jacqueline-gordon-palmer',
    reviewer: 'Jacqueline Gordon Palmer',
    headline: 'Ethan was very helpful and patient…',
    rating: 5,
    country: 'US',
    reviewCount: 1,
    date: 'June 15, 2022',
    body: ['Ethan was very helpful and patient especially to someone that is not technically skilled. The team seemed experienced in creating the site I want. The site is not online for sales at this point. Hopefully it can get functional Immediately so I can get selling.'],
  },
  {
    id: 'style-loft',
    reviewer: 'Style Loft',
    headline: 'Thank You Crystal Web Solution',
    rating: 5,
    country: 'US',
    reviewCount: 2,
    date: 'June 14, 2022',
    body: ['It have been an amazing adventure working with Crystal Web Solution. Thanks to their knowledge and determination my website looks great and functions really good. Ethan and the team of developers have been very patient with me and extremely helpful in guiding me through the whole process. They are very knowledgeable. Ive manly been working with Ethan and he pays close attention to details. He is also very patient in training me on how to use the Wordpress back office system. I will be recommending anyone that is looking for a custom website to give them a call and speak to Ethan, he will guide you in the right direction.'],
  },
];

const FEATURED_IDS = [
  'porsha-patterson',
  'vaughn-hebron',
  'sneha-yendluri',
  'rose-filicetti',
  'marcus',
  'ahmed-jeffrey',
];

export const FEATURED_REVIEWS = FEATURED_IDS.map((id) => REVIEWS.find((review) => review.id === id));

export const REVIEW_STATS = {
  total: REVIEWS.length,
  average: (REVIEWS.reduce((sum, review) => sum + review.rating, 0) / REVIEWS.length).toFixed(1),
  positive: REVIEWS.filter((review) => review.rating >= 4).length,
  latest: REVIEWS[0].date,
};
